services:
  rag-core:
    build:
      context: ./rag_core
      dockerfile: Dockerfile
    container_name: rag_core
    # Пробрасывать порт наружу не обязательно, он доступен только внутри сети Docker
    expose:
      - "8001"
    volumes:
      - ./rag_core/data:/app/data
      - ./rag_core/logs:/app/logs
      - hf_cache:/root/.cache/huggingface
    environment:
      - HF_HOME=/root/.cache/huggingface
    networks:
      - rag_network
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

  web-api:
    build:
      context: ./web_api
      dockerfile: Dockerfile
    container_name: rag_web_api
    ports:
      - "8000:8000" # Этот порт торчит наружу для пользователей
    environment:
      # Важно: "rag-core" совпадает с именем сервиса выше
      - RAG_CORE_URL=http://rag-core:8001 
    depends_on:
      - rag-core
    networks:
      - rag_network
    restart: unless-stopped

networks:
  rag_network:
    driver: bridge

volumes:
  hf_cache:
    name: rag_hf_cache